### ISSUE TITLE
Crash on startup, fatal sql error?

### ISSUE THREAD

**Issue by eyeonus** [Duke-Jones/ED-IBE#13] opened 2016-07-22 06:39 UTC
Data dump: https://drive.google.com/open?id=0B2q7KyznfswHMFpXazYtSmFSMVU

[App_2016-07-22 00-12-01.log.txt](https://github.com/Duke-Jones/ED-IBE/files/377583/App_2016-07-22.00-12-01.log.txt)
[Exception_2016-07-22 00-12-01.log.txt](https://github.com/Duke-Jones/ED-IBE/files/377584/Exception_2016-07-22.00-12-01.log.txt)

**Comment by eyeonus** [comment] 2016-08-01 19:15
Seriously? No one has even looked at this yet? I would think a fatal error on a brand new install that hasn't even successfully launched yet would be a pretty important issue.

**Comment by Duke-Jones** [comment] 2016-09-28 20:10
Sorry for this. I do not get any money for this project (except some rare donations with PayPal)
and so I felt free to go and have some fun during this summer
like beer drinking, meet some friends, visit metal festivals, driving my motorbike,
go wakeboarding and so on :D 

But now, when the temperatures are goin' down and the days 
become shorter I'm more and more back on this project.

I think it makes no sense to check your old problems on the old v0.3.3
and so I suggest to wait for the coming v0.4.0 and check if the problem is still existing.

**Comment by eyeonus** [comment] 2016-09-30 18:09
Alright. Let me know when 0.4 is out then, I guess?

**Comment by Duke-Jones** [comment] 2016-10-01 08:13
Yes, I will post it in the forums

**Comment by Duke-Jones** [comment] 2016-10-08 07:48
should be fixed in v0.4.0
(https://github.com/Duke-Jones/ED-IBE/tree/v0.4.0)

**Comment by eyeonus** [comment] 2016-10-08 10:39
Nope.
https://goo.gl/photos/YkBLyxXHPpcFXCgu5

**Comment by Duke-Jones** [comment] 2016-10-08 10:44
Looks like your sql server ist not running. Have you installed v040 in a clean directory? 

Am 8. Oktober 2016 12:39:28 MESZ, schrieb Jonathan Jones notifications@github.com:

> Nope.
> https://goo.gl/photos/YkBLyxXHPpcFXCgu5
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/Duke-Jones/ED-IBE/issues/13#issuecomment-252417600

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Duke-Jones** [comment] 2016-10-08 15:50
have you read position 1 of the start tips files ? : 

> 1. Installation
>    By default, the program installs to half in the Programs
>    directory (C:\Program Files\ED-IBE) and the other half in the data directory
>    (C:\Users{USER}\AppData\Local\ED-IBE). These paths can during installation
>    be adjusted. You also can specify the same directory for both parts (eg. "F:\ED-IBE").
> 
> At the end of the installation should go up for a few moments a cmd window.
> During this time the database structure is created. If this window does not appear,
> something is wrong. Possibly try re-installing in another destination directory.
> A log of this action can be found in the data directory, if you experience problems.
> (.\ED-IBE\Database\install.log).
> 
> If you perform an update the setup routine recognizes an existing 
> database by the existence of the file ".\ED-IBE\Database\data\ibdata1".
> The database will be left unchanged, unless explicitly wanted due to 
> the selection of "Delete and re-create" in the setup dialogs.
> Case something goes wrong and you want to delete the database again, you have to
> run the installer again and check the checkbox for "Delete and re-create."
> But have in mind all data will be lost.

Have you seen the black windows after a clean installation ?
If not you possibly have running a security software that prevents a clean installation ?
If you have seen the black window upload the log from .\ED-IBE\Database\install.log.
Possibly I can help then .

**Comment by eyeonus** [comment] 2016-10-08 18:14
Clean install to the same location as the previous version-- manually deleted all files and folders in the top level folder, and checked the box that said "Delete all existing data and re-create the database". A black window did appear. "2016-10-08 12:11:40 0 [Note] bin\mysqld.exe (mysqld 5.6.29) starting as process 158504 ..." Then it went away. The time was different the first time I did this, obviously.

I've even tried running the installer with admin rights.

**Comment by eyeonus** [comment] 2016-10-08 18:15
[install.log.txt](https://github.com/Duke-Jones/ED-IBE/files/517855/install.log.txt)

**Comment by Duke-Jones** [comment] 2016-10-08 18:36
hm, ok. database was created correctly.

Please try to start the database manually.
Go to the script folder and start "start_server.cmd" 
A cmd window should appear which normally (if the server is started by ED-IBE)
is hidden. There should be no errors and the last line should show something like

> 2016-10-08 20:33:59 0 [Note] .\bin\mysqld.exe (mysqld 5.6.29) starting as process 7384 ...

Leave this window open and start ED-IBE. 

What happens ?

**Comment by eyeonus** [comment] 2016-10-08 19:57
It's currently importing systems, it looks like everything is working fine now. Why isn't the sql server starting automatically like it's supposed to?

**Comment by eyeonus** [comment] 2016-10-08 20:02
Also, minor bit of annoyance-- the intro window thing is in always on top mod, and immovable, and taking up a huge portion of the center of my screen, making it VERY difficult to do anything other than wait for it to finish and go the hell away while I'm waiting for it to finish and go the hell away, and it's taken like 10 minutes so far. IMO, Database updates should really not be done in that window, like ever.

No disrespect intended.

**Comment by Duke-Jones** [comment] 2016-10-08 20:16
> Why isn't the sql server starting automatically like it's supposed to? 

No idea but I'm assuming there's a problem with the path. I saw you 
took S:\Steam\steamapps\common\Elite Dangerous\Trade Dangerous\ED-IBE\
Possibly there are problems agin with updates. You should try to 
install IBE in another flat directory structure like 
S:\EDTools\ED-IBE
or try 
D:\EDTools\ED-IBE
maybe it's a problem with "S:"

Can you post your ED-IBE.ini , please ?

> Also, minor bit of annoyance........ 

Sorry for this. Do do my very best, but to write such a (not really simple) software 
need the full attention also many other aspects and so different parts are simply unsatisfying.
I have my work, my family , real life **and** E:D and sometimes I find a few hours for developing ;-)

**Comment by eyeonus** [comment] 2016-10-08 20:21
## ED-IBE.ini:

[DB_Server]
Commandline="S:\Steam\steamapps\common\Elite Dangerous\Trade Dangerous\ED-IBE\Database\bin\mysqld.exe"
CommandArgs=--defaults-file="S:\Steam\steamapps\common\Elite Dangerous\Trade Dangerous\ED-IBE\Database\Elite.ini" --console
WorkingDirectory="S:\Steam\steamapps\common\Elite Dangerous\Trade Dangerous\ED-IBE\Database"
Port=3306

DBStartTimeout=60

[DB_Connection]
Name=master
Server=localhost

Database=Elite_DB

User=RN_User

Pass=Elite

ConnectTimeout=60

StayAlive=false

TimeOut=10000

---

Call me a grammar nazi if you wish, but "around of 20 ly of" is not correct. I suggest "within 20 ly of".

**Comment by Duke-Jones** [comment] 2016-10-08 20:29
haha, my english is absolutely bad - I'm glad you understand me ;-)
You will find more grammar mistakes but if you tell me what is wrong I 
will consider this in the next releases.

Possibly the path ist too long for the sql server to point to the defaults file:

> --defaults-file="S:\Steam\steamapps\common\Elite Dangerous\Trade Dangerous\ED-IBE\Database\Elite.ini

You really should try this with a shorter path.

**Comment by eyeonus** [comment] 2016-10-08 20:58
Yup, it's the path. I tried changing it to ".\Database\Elite.ini", which works, but I still had to move it. So I symlinked it to C:\ED-IBE and it's working, although for some reason only the system I'm currently at shows up in the Price Analysis tab even though I told the thing to import the everything.

**Comment by eyeonus** [comment] 2016-10-08 21:06
I get this when trying to import manually from the downloaded csv:

## Exception.log:

## 08.10.2016 15:05:07 : 08.10.2016 21:05:07 : Error while importing from csv

08.10.2016 21:05:07 : Error while importing self collected price data
08.10.2016 21:05:07 :    at IBE.SQL.EliteDBIO.ImportPricesFromCSVFile(String filename, enImportBehaviour importBehaviour, enDataSource dataSource, PriceImportParameters importParams) in E:\dev\RN\ED-IBE\ED-IBE\SQL\EliteDBIO.cs:line 2711
   at IBE.frmDataIO.<>c__DisplayClass41_1.<cmdImportFromCSV_Click>b__0() in E:\dev\RN\ED-IBE\ED-IBE\frmDataIO.cs:line 1293
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

##    at IBE.frmDataIO.<cmdImportFromCSV_Click>d__41.MoveNext() in E:\dev\RN\ED-IBE\ED-IBE\frmDataIO.cs:line 1295

08.10.2016 21:05:07 : Error while importing self collected price data
08.10.2016 21:05:07 :    at IBE.SQL.EliteDBIO.ImportPricesFromEDDBStrings(String[] CSV_Strings, enImportBehaviour importBehaviour, enDataSource dataSource, PriceImportParameters importParams) in E:\dev\RN\ED-IBE\ED-IBE\SQL\EliteDBIO.cs:line 3045

##    at IBE.SQL.EliteDBIO.ImportPricesFromCSVFile(String filename, enImportBehaviour importBehaviour, enDataSource dataSource, PriceImportParameters importParams) in E:\dev\RN\ED-IBE\ED-IBE\SQL\EliteDBIO.cs:line 2707

08.10.2016 21:05:07 : Object reference not set to an instance of an object.
08.10.2016 21:05:07 :    at IBE.SQL.EliteDBIO.ImportPricesFromEDDBStrings(String[] CSV_Strings, enImportBehaviour importBehaviour, enDataSource dataSource, PriceImportParameters importParams) in E:\dev\RN\ED-IBE\ED-IBE\SQL\EliteDBIO.cs:line 3000

---

---

**Comment by Duke-Jones** [comment] 2016-10-08 23:14
I assume you've done a import of new downloaded EDDB data with import of price data ?
Which have you selected ? 20ly bubble or all ?

**Comment by eyeonus** [comment] 2016-10-08 23:18
Yup. And I've tried it with both.

**Comment by Duke-Jones** [comment] 2016-10-08 23:31
> Yup, it's the path. I tried changing it to ".\Database\Elite.ini", which works, but I still had to move it. So I >symlinked it to C:\ED-IBE and it's working, although for some reason only the system I'm currently at >shows up in the Price Analysis tab even though I told the thing to import the everything.

Ok fine to get a explanation for this behaviour.

For your other problem: 
- be sure your current system recognized in the upper right textbox.
- be sure the "station filter"->"only include stations within....... lightyears of <crtitical>" shows as critical "<current system>"
- be sure, if you import "bubble price data" your current system, shown in the upper right textbox, is really your current system - otherwise do the price import again with the correct acknowledged system
- if it's still suspicious try to restart ED-IBE (everytime a good idea on suspicious behaviour ;-)  )

... it's not easy .... :-)

**Comment by Duke-Jones** [comment] 2016-10-08 23:32
> Yup. And I've tried it with both.

and everytime you stuck with this error ? 
.. or was it a one time error ?

**Comment by eyeonus** [comment] 2016-10-08 23:34
So far. I haven't tried the most recent suggestion yet, I'm having dinner right now.

**Comment by Duke-Jones** [comment] 2016-10-08 23:37
Ok, I'll go to bed now. It's late ....  or early ....whatever...

"see" you again tomorow

**Comment by Duke-Jones** [comment] 2016-10-09 09:30
hi there.

I took a look into the code and I realized that you pressed "Import Marketdata from CSV".
Is this correct ?

This button (and all other in the "Market Data (CSV)" groupbox) is only for exchange market data between two installations of IBE or between IBE and another program.
If you simply want to load EDDB data (systems/stations and also prices) you only have to use the buttons in "EDDB imports" groupbox.

**Comment by eyeonus** [comment] 2016-10-10 01:59
> For your other problem:
> -     be sure your current system recognized in the upper right textbox.

Yup.

> -     be sure the "station filter"->"only include stations within....... lightyears of " shows as critical ""

Check.

> -     be sure, if you import "bubble price data" your current system, shown in the upper right textbox, is really your current system - otherwise do the price import again with the correct acknowledged system

Tried that.

> -     if it's still suspicious try to restart ED-IBE (everytime a good idea on suspicious behaviour ;-) )

Multiple times. Now it shows four systems instead of two.

These are the import settings.:
https://goo.gl/photos/QTEVNXSJrmV9B9Z78

These are the stations it finds at most regardless of search settings.:
https://goo.gl/photos/iJxSHEhJVWaN5jcd6

**Comment by Duke-Jones** [comment] 2016-10-10 14:43
I think the price import have not finished. Assuming you have activated EDDN for recieving 
price data directly, only the data from LHS 122 ist your self collected data. The other stations are probably
from EDDN ? You can see the souce the if you select on of them and then look into the column "Source".

I'm testing at the moment - found got also an error when I tyr to import ALL prices.....

**Comment by Duke-Jones** [comment] 2016-10-10 15:31
I found a error in cause of this the full import does not work.
But the bubble import should work ?!

On the screenshots you can see the messages after a successful import.
You may compare this with your messages.

bubble import : https://www.dropbox.com/s/2b2j4zmn7boberp/2016-10-10%2017_25_49-Data%20Interface_bub.png?dl=0
full import https://www.dropbox.com/s/m44axhcapx3xx7q/2016-10-10%2017_23_19-Data%20Interface.png?dl=0

I will release v0.4.1 this evening with this error fixed, so please be patient

**Edit: Important tip !!!!!:** Avoid to remove all the filters as you did in the screenshot. If you have a lot of data in your database (e..g. after a full import) you can get time-out problems when doing sql-querys (specially when you also set a large trading distance)

**Comment by eyeonus** [comment] 2016-10-10 18:13
> The other stations are probably from EDDN ?

Yes. I haven't done any traveling while trying to get the program working, so it's definite the only station not from EDDB is the one I'm at right now.

> Avoid to remove all the filters

Yes, I am aware just how huge the full database is, I wouldn't have done an unfiltered search if we weren't testing right now. :D

Speaking of, after doing another bubble import, the unfiltered search has gotten up to 126 stations and 47 systems, so that seems to have worked.

**Comment by Duke-Jones** [comment] 2016-10-10 18:46
just released the v0.4.1.

When you import price data and still have problems, compare your messages with the messages on my pictures from the post above. But I hope everything will work now.

**Comment by eyeonus** [comment] 2016-10-14 20:23
Sorry for how long it's been. Had other things going on IRL.

It seems to be working fine now, thanks for that.

**Comment by Duke-Jones** [comment] 2016-10-14 21:16
you're welcome. Thanks for your response.

**Closed as completed by Duke-Jones** 2016-10-14 21:16 UTC
Labels: bug, in progress
